## **Homework 6:** Direct Methods for Linear Systems
TJ Scanlan<br>*Merrimack College*<br>*MTH3725 Numerical Analysis*<br>*Spring 2023*

In [1]:
#importing np for matrix algebra, scipy for matrix manipulation and system solving
import numpy as np
from scipy.linalg import lu, lu_factor, lu_solve, hilbert

### **Problem 1:** Partial pivoting and finite-digit arithmetic
Use Gaussian elimination without partial pivoting, then with partial pivoting, to solve the following system. ***After each intermediate step, round to three decimal places.*** $$ 0.03x_1 + 58.9x_2 = 59.2 $$ $$ 5.31x_1 - 6.10x_2 = 47.0 $$

In [6]:
A = np.array([0.03,58.9,5.31,-6.10]).reshape([2,2])
b = np.array([59.2,47.0]).reshape([2,1])
np.set_printoptions(suppress=True)
print(A)
print(b)

[[ 0.03 58.9 ]
 [ 5.31 -6.1 ]]
[[59.2]
 [47. ]]


### **Problem 2:** Error and condition numbers
Find the relative forward and backward errors and error magnification factors for the following approximations of the system $$ x_1 + 2x_2 = 3 $$ $$ 2x_1 + 4.01x_2 = 6.01 $$
a) [-10, 6] <br>
b) [-100, 52] <br>
c) [-600, 301] <br>
d) [-599, 301] <br>
e) What is the condition number of A? 

### **Problem 3:** Setting up and solving a linear system
Imagine we have a 1 m long thin metal rod heated to $ 100^{\circ} C $ on the left side and cooled to $ 0^{\circ} C $ on the right. We want to know the temperature every 10 cm from the left end to the right end of the rod. <br><br>
a) First, break down the rod into equal 10 cm increments as shown below. How many unknowns are there? <br>
b) Use this formula to find the temperature at each point. Write a system of equations for each unknown. $$ T_1 = \frac{T_0 + T_2}{2} $$
c) Solve the system at each unknown using $ PA = LU $ decomposition. <br>
d) Use the $ PA = LU $ factorization to find the temperature at each node if the left side is held at $ 50^{\circ} C $ and the right side is $ 20^{\circ} C $.

In [7]:
A = np.array([2,-1,0,0,0,0,0,0,0,-1,-2,-1,0,0,0,0,0,0,0,-1,2,-1,0,0,0,0,0,0,0,-1,2,-1,0,0,0,0,0,0,0,-1,2,-1,0,0,0,0,0,0,0,-1,2,-1,0,0,0,0,0,0,0,0,-1,2,-1,0,0,0,0,0,0,-1,2,-1,0,0,0,0,0,0,0,-1,2]).reshape([9,9])
b = np.array([100,0,0,0,0,0,0,0,0]).reshape([9,1])
LUA, PivA = lu_factor(A)
x = lu_solve((LUA,PivA), b)
print(x) #rod at 100C on left
bb = np.array([20,0,0,0,0,0,0,0,0]).reshape([9,1])
xx = lu_solve((LUA,PivA),bb)
print(xx) #rod at 50C on left and 20C on right

[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]
[[nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]
 [nan]]


/var/folders/w2/jd0dpx7s1rn5zgnb46fy50cm0000gn/T/ipykernel_3836/1965338940.py:3: LinAlgWarning: Diagonal number 9 is exactly zero. Singular matrix.
  LUA, PivA = lu_factor(A)


### **Problem 4:** $ PA = LU $ Factorization
Solve the system by finding the $ PA = LU $ factorization and then carrying out the two-step back substitution.
$$ \begin{pmatrix} 3 & 1 & 2 \\ 6 & 3 & 4 \\ 3 & 1 & 5 \end{pmatrix} \begin{pmatrix} x_1 \\ x_2 \\ x_3 \end{pmatrix} = \begin{pmatrix} 0 \\ 1 \\ 3 \end{pmatrix} $$

### **Problem 5:** Solving linear systems with an ill-conditioned matrix
Let $ H $ denote the $ n $ x $ n $ Hilbert matrix, whose $ (i,j) $ entry is $ H_i,_j = \frac{1}{i + j - 1} $. Use a built-in method to solve $ H\vec{x} = \vec{b} $, where $\vec{b}$ is the vector of all ones, for $n = 5$, $n = 10$, and $n = 15$. Find each of the condition numbers of each Hilbert matrix, as well.

In [8]:
h5 = hilbert(5)
h10 = hilbert(10)
h15 = hilbert(15)

LU5, piv5 = lu_factor(h5)
b5 = np.ones((5,1))
x5 = lu_solve((LU5, piv5), b5)
np.set_printoptions(suppress=True)
print("Solution for n=5:\n",x5)

LU10, piv10 = lu_factor(h10)
b10 = np.ones((10,1))
x10 = lu_solve((LU10, piv10), b10)
np.set_printoptions(suppress=True)
print("Solution for n=10:\n",x10)

LU15, piv15 = lu_factor(h15)
b15 = np.ones((15,1))
x15 = lu_solve((LU15, piv15), b15)
np.set_printoptions(suppress=True)
print("Solution for n=15:\n",x15)

Solution for n=5:
 [[    5.        ]
 [ -120.        ]
 [  630.        ]
 [-1120.00000001]
 [  630.        ]]
Solution for n=10:
 [[      -9.99982337]
 [     989.98462136]
 [  -23759.6706349 ]
 [  240236.99215467]
 [-1261245.59668115]
 [ 3783740.26704767]
 [-6726654.60603584]
 [ 7001216.62539424]
 [-3938186.64337611]
 [  923772.64719902]]
Solution for n=15:
 [[ 1.30605454e+01]
 [-1.91518043e+03]
 [ 6.81385554e+04]
 [-1.02090629e+06]
 [ 7.89148860e+06]
 [-3.39557552e+07]
 [ 7.85050678e+07]
 [-6.12057325e+07]
 [-1.50759285e+08]
 [ 4.84649789e+08]
 [-5.78785639e+08]
 [ 2.86377328e+08]
 [ 3.50544305e+07]
 [-9.52825111e+07]
 [ 2.84656739e+07]]
