# **Homework 5: Vectors and Matrices**

# TJ Scanlan

In [1]:
import numpy as np

Problem #1

In [2]:
#1a)
A = np.array([[1,3,5,7],[2,4,6,8],[-3,-2,-1,0]])
u = np.array([[10],[20],[30]])
print("A:")
print(A)
print("Dimensions of A:", np.size(A))
print("")
print("u:")
print(u)
print("Dimensions of u:", np.size(u))

A:
[[ 1  3  5  7]
 [ 2  4  6  8]
 [-3 -2 -1  0]]
Dimensions of A: 12

u:
[[10]
 [20]
 [30]]
Dimensions of u: 3


In [3]:
#1b
print("First column of A:\n", A[:,0])

First column of A:
 [ 1  2 -3]


In [4]:
#1c
print("First row of A:\n", A[0])

First row of A:
 [1 3 5 7]


In [5]:
#1d
print("First 2 entries of u:\n", u[:2])

First 2 entries of u:
 [[10]
 [20]]


In [6]:
#1e
print("Last 2 entries of u:\n", u[1:])

Last 2 entries of u:
 [[20]
 [30]]


In [7]:
#1f
subA = A[np.ix_([1,2],[0,1])]
print("Lower left submatrix of A:\n", subA)

Lower left submatrix of A:
 [[ 2  4]
 [-3 -2]]


In [8]:
#1g
midA = A[np.ix_([1],[1,2])]
print("Middle two elements of middle row of A:\n", midA)

Middle two elements of middle row of A:
 [[4 6]]


Problem #2

*insert work*

Problem #3

*insert work*

Problem #4

In [20]:
u = np.array([[2],[0],[5]])
v = np.array([[-6],[3],[4]])
A = np.array([[-1,1],[0,2]])
B = np.array([[8,-2],[1,3]])
C = np.array([[1,3,0],[-4,-1,1]])
print("i.", u + v)
print("ii.",v - u)
print("iii.",(-3)*u)
print("iv.", A+B)
print("v. B+C non-calculable")
print("vi.", (0.5)*B)
print("vii.", (2*A)-B)
print("viii.", C.transpose())


i. [[-4]
 [ 3]
 [ 9]]
ii. [[-8]
 [ 3]
 [-1]]
iii. [[ -6]
 [  0]
 [-15]]
iv. [[ 7 -1]
 [ 1  5]]
v. B+C non-calculable
vi. [[ 4.  -1. ]
 [ 0.5  1.5]]
vii. [[-10   4]
 [ -1   1]]
viii. [[ 1 -4]
 [ 3 -1]
 [ 0  1]]


Problem #5

In [39]:
D = np.matrix([[1,1,2],[1,0,1]])
E = np.matrix([[3,1],[2,1],[1,0]])
F = np.matrix([[4,2],[-1,1]])
x = np.array([[2],[-2]])
print("i.", D*E)
print("ii.", E*D)
#print("iii.", D*F)
print("iv.", F*D)
#print("v.", D*D)
print("vi.", F**2)
print("vii.", E*x)
print("viii.", F*x)

i. [[7 2]
 [4 1]]
ii. [[4 3 7]
 [3 2 5]
 [1 1 2]]
iv. [[ 6  4 10]
 [ 0 -1 -1]]
vi. [[14 10]
 [-5 -1]]
vii. [[4]
 [2]
 [2]]
viii. [[ 4]
 [-4]]
