# **Implementing LU-factorization in Python**

Using Python to solve $ A \vec{x} = \vec{b} $ using LU-factorization...
$$ A = \begin{pmatrix} -1 & 0 & 1 \\ 2 & 1 & 1 \\ -1 & 2 & 0 \end{pmatrix}, \:\vec{b} = \begin{pmatrix} -2 \\ 17 \\ 3 \end{pmatrix}$$
LU-factorization comes as a built-in package in the ***.linalg* library of the SciPy package**. Note how we write the A matrix a little differently. The **.reshape()** command allows us to write the matrix entries as one list within np.array where the size of the size of the matrix is a list inside the command.


In [13]:
#Importing packages
import numpy as np
from scipy.linalg import lu_factor, lu_solve, lu

In [4]:
A = np.array([-1,0,1,2,1,1,-1,2,0]).reshape([3,3])

In [11]:
LU, piv = lu_factor(A) #make sure to define LU in capital letters to avoid a 'callable' error!!
print("LU:\n",LU)
print("\nPiv:\n", piv)

LU:
 [[ 2.   1.   1. ]
 [-0.5  2.5  0.5]
 [-0.5  0.2  1.4]]

Piv:
 [1 2 2]


In [12]:
b = np.array([-2,17,3]) #no need for .reshape() since b is a vector
x = lu_solve((LU,piv),b)
print("x:\n", x)

x:
 [5. 4. 3.]


**Using the *lu* package from the SciPy (linalg) library.**
Note how the the "p" matrix here is different from the one we used in class notes. This is OK! It's still a permutation matrix, just the inverse of the one used in class.

In [15]:
p,l,u = lu(A)
print("p:\n", p, "\nl:\n", l, "\nu:\n", u)

p:
 [[0. 0. 1.]
 [1. 0. 0.]
 [0. 1. 0.]] 
l:
 [[ 1.   0.   0. ]
 [-0.5  1.   0. ]
 [-0.5  0.2  1. ]] 
u:
 [[2.  1.  1. ]
 [0.  2.5 0.5]
 [0.  0.  1.4]]
